const routes = [
  {
    path: "index.html",
    label: "Home",
    classification: "public",
    stack: "modern public",
    dataSource: "public-data.js",
    robots: "index,follow",
    smoke: true,
    shellSmoke: true,
    accessibilitySmoke: true,
    expectedText: "Pawn Island"
  },
  {
    path: "roster.html",
    label: "Roster",
    classification: "public",
    stack: "modern public",
    dataSource: "public-data.js",
    robots: "index,follow",
    smoke: true,
    shellSmoke: true,
    accessibilitySmoke: true,
    expectedText: "Roster & Projects"
  },
  {
    path: "connect.html",
    label: "Connect",
    classification: "public",
    stack: "modern public",
    dataSource: "public-data.js",
    robots: "index,follow",
    smoke: true,
    shellSmoke: true,
    accessibilitySmoke: true,
    expectedText: "Signals from the Island"
  },
  {
    path: "about.html",
    label: "About",
    classification: "public",
    stack: "modern public",
    dataSource: "public-data.js",
    robots: "index,follow",
    smoke: true,
    shellSmoke: true,
    accessibilitySmoke: true,
    expectedText: "About Pawn Island Records"
  },
  {
    path: "catalog.html",
    label: "Catalog",
    classification: "hidden-but-shareable",
    stack: "modern public",
    dataSource: "public-data.js",
    robots: "noindex,follow",
    smoke: true,
    expectedText: "The full catalog page is tucked away for launch."
  },
  {
    path: "catalog.html?preview=full",
    label: "Catalog Full Preview",
    classification: "hidden-but-shareable",
    stack: "modern public",
    dataSource: "public-data.js",
    robots: "noindex,follow",
    smoke: true,
    shellSmoke: true,
    accessibilitySmoke: true,
    expectedText: "Forthcoming Releases",
    absentText: ["Launch Mode", "tucked away", "staying private"],
    expectedTitle: "Catalog | Pawn Island Records",
    expectedMetaDescription: "Explore the Pawn Island Records catalog",
    expectedCanonical: "https://www.pawnislandrecords.com/catalog.html",
    expectedJsonLd: "CollectionPage"
  },
  {
    path: "catalog.html?artist=rhea-mauro",
    label: "Catalog Artist Filter",
    classification: "hidden-but-shareable",
    stack: "modern public",
    dataSource: "public-data.js",
    robots: "noindex,follow",
    expectedText: "The full catalog page is tucked away for launch."
  },
  {
    path: "catalog.html?artist=rhea-mauro&preview=full",
    label: "Catalog Artist Full Preview",
    classification: "hidden-but-shareable",
    stack: "modern public",
    dataSource: "public-data.js",
    robots: "noindex,follow",
    smoke: true,
    expectedText: "Rhea Mauro:",
    absentText: ["Launch Mode", "tucked away", "staying private"],
    expectedTitle: "Rhea Mauro | Catalog | Pawn Island Records",
    expectedMetaDescription: "catalog filtered by Rhea Mauro",
    expectedCanonical: "https://www.pawnislandrecords.com/catalog.html?artist=rhea-mauro",
    expectedJsonLd: "CollectionPage"
  },
  {
    path: "artist.html?artist=rhea-mauro",
    label: "Project Detail",
    classification: "hidden-but-shareable",
    stack: "modern public",
    dataSource: "public-data.js",
    robots: "noindex,follow",
    smoke: true,
    expectedText: "Project pages are staying private for launch."
  },
  {
    path: "artist.html?artist=rhea-mauro&preview=full",
    label: "Project Detail Full Preview",
    classification: "hidden-but-shareable",
    stack: "modern public",
    dataSource: "public-data.js",
    robots: "noindex,follow",
    smoke: true,
    shellSmoke: true,
    accessibilitySmoke: true,
    expectedText: "Project Releases",
    absentText: ["Launch Mode", "tucked away", "staying private"],
    expectedTitle: "Rhea Mauro | Pawn Island Records",
    expectedMetaDescription: "Rhea Mauro",
    expectedCanonical: "https://www.pawnislandrecords.com/artist.html?artist=rhea-mauro",
    expectedJsonLd: "MusicGroup"
  },
  {
    path: "release.html?release=rhea-mauro-hearthblood",
    label: "Release Detail",
    classification: "hidden-but-shareable",
    stack: "modern public",
    dataSource: "public-data.js",
    robots: "noindex,follow",
    smoke: true,
    expectedText: "Release pages are staying private for launch."
  },
  {
    path: "release.html?release=rhea-mauro-hearthblood&preview=full",
    label: "Release Detail Full Preview",
    classification: "hidden-but-shareable",
    stack: "modern public",
    dataSource: "public-data.js",
    robots: "noindex,follow",
    smoke: true,
    shellSmoke: true,
    accessibilitySmoke: true,
    expectedText: "Official Audio",
    absentText: ["Launch Mode", "tucked away", "staying private"],
    expectedTitle: "Hearthblood | Rhea Mauro | Pawn Island Records",
    expectedMetaDescription: "Hearthblood by Rhea Mauro",
    expectedCanonical: "https://www.pawnislandrecords.com/release.html?release=rhea-mauro-hearthblood",
    expectedJsonLd: "MusicAlbum"
  },
  {
    path: "epks.html",
    label: "Press Index",
    classification: "hidden-but-shareable",
    stack: "modern public",
    dataSource: "public-data.js",
    robots: "noindex,follow",
    smoke: true,
    expectedText: "Press pages are staying private for launch."
  },
  {
    path: "epks.html?preview=full",
    label: "Press Index Full Preview",
    classification: "hidden-but-shareable",
    stack: "modern public",
    dataSource: "public-data.js",
    robots: "noindex,follow",
    smoke: true,
    shellSmoke: true,
    accessibilitySmoke: true,
    expectedText: "Open Press Kit",
    absentText: ["Launch Mode", "tucked away", "staying private"],
    expectedTitle: "Press | Pawn Island Records",
    expectedMetaDescription: "Browse source-approved Pawn Island Records project press kits",
    expectedCanonical: "https://www.pawnislandrecords.com/epks.html",
    expectedJsonLd: "CollectionPage"
  },
  {
    path: "epk.html?artist=rhea-mauro",
    label: "Press Kit",
    classification: "hidden-but-shareable",
    stack: "modern public",
    dataSource: "public-data.js",
    robots: "noindex,follow",
    smoke: true,
    expectedText: "Press kits are staying private for launch."
  },
  {
    path: "epk.html?artist=rhea-mauro&preview=full",
    label: "Press Kit Full Preview",
    classification: "hidden-but-shareable",
    stack: "modern public",
    dataSource: "public-data.js",
    robots: "noindex,follow",
    smoke: true,
    shellSmoke: true,
    accessibilitySmoke: true,
    expectedText: "Kit Views",
    absentText: ["Launch Mode", "tucked away", "staying private"],
    expectedTitle: "Rhea Mauro Press Kit | Pawn Island Records",
    expectedMetaDescription: "Rhea Mauro press kit",
    expectedCanonical: "https://www.pawnislandrecords.com/epk.html?artist=rhea-mauro",
    expectedJsonLd: "ProfilePage"
  },
  {
    path: "epk.html?artist=high-ground&preview=full",
    label: "Press Kit Hold Preview",
    classification: "hidden-but-shareable",
    stack: "modern public",
    dataSource: "public-data.js",
    robots: "noindex,follow",
    smoke: true,
    accessibilitySmoke: true,
    expectedText: "Press kit is available by request.",
    absentText: ["Kit Views", "Open Press Kit"],
    expectedTitle: "High Ground Press Kit By Request | Pawn Island Records",
    expectedMetaDescription: "High Ground press materials are available by request",
    expectedCanonical: "https://www.pawnislandrecords.com/epk.html?artist=high-ground"
  },
  {
    path: "process.html",
    label: "Creative Process",
    classification: "hidden-but-shareable",
    stack: "story",
    dataSource: "public-data.js",
    robots: "noindex,follow",
    smoke: true,
    shellSmoke: true,
    expectedText: "My music begins with intention."
  },
  {
    path: "merch.html",
    label: "Merch Desk",
    classification: "hidden-but-shareable",
    stack: "modern public",
    dataSource: "public-data.js",
    robots: "noindex,follow",
    smoke: true,
    shellSmoke: true,
    accessibilitySmoke: true,
    expectedText: "Curated artist tees, desk mats, and carry goods",
    expectedTitle: "Merch Desk | Pawn Island Records",
    expectedMetaDescription: "Browse curated Pawn Island Records artist goods",
    expectedCanonical: "https://www.pawnislandrecords.com/merch.html",
    expectedJsonLd: "CollectionPage"
  },
  {
    path: "campaigns.html",
    label: "Campaign Lab",
    classification: "internal-lab",
    stack: "legacy lab",
    dataSource: "data.js",
    robots: "noindex,nofollow",
    smoke: true,
    expectedText: "Campaign Lab"
  },
  {
    path: "brand-kit.html",
    label: "Brand Kit",
    classification: "internal-lab",
    stack: "legacy lab",
    dataSource: "data.js",
    robots: "noindex,nofollow",
    smoke: true,
    expectedText: "Brand Kit"
  },
  {
    path: "release-deck.html",
    label: "Release Deck",
    classification: "internal-lab",
    stack: "standalone product page",
    dataSource: "static html",
    robots: "noindex,nofollow",
    smoke: true,
    expectedText: "Release Deck"
  },
  {
    path: "admin.html",
    label: "Catalog Editor",
    classification: "admin-only",
    stack: "admin",
    dataSource: "public-data.js",
    robots: "noindex,nofollow",
    expectedText: "Catalog Editor"
  },
  {
    path: "shell.html",
    label: "Persistent Shell",
    classification: "shell",
    stack: "shell",
    dataSource: "iframe target",
    robots: "noindex,follow",
    expectedText: "Loading the next world."
  },
  {
    path: "artists.html",
    label: "Artists Redirect",
    classification: "redirect",
    stack: "redirect shim",
    dataSource: "static html",
    robots: "noindex,follow",
    expectedText: "Redirecting"
  }
];

module.exports = {
  routes,
  accessibilitySmokeRoutes: routes.filter((route) => route.accessibilitySmoke),
  smokeRoutes: routes.filter((route) => route.smoke),
  shellSmokeRoutes: routes.filter((route) => route.shellSmoke)
};
